# -*- coding: utf-8 -*-
"""Lotto alfabet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q70eZFK9bkthMhmJVXWgCSN1Ei5VGInc
"""

# Install gradio
!pip install gradio -q

import gradio as gr
import random
import string

# Save game state
game_state = {
    "secret": "",
    "attempts": 0,
    "game_over": False
}

# Start new game
def start_game(level):

    # Difficulty setting
    if level == "Easy":
        attempts = 10

    elif level == "Medium":
        attempts = 7

    else:
        attempts = 5

    # Random secret letter
    secret = random.choice(list(string.ascii_uppercase))

    # Save state
    game_state["secret"] = secret
    game_state["attempts"] = attempts
    game_state["game_over"] = False

    return f"""
# 🎮 GAME STARTED

🎚️ Difficulty : {level}

🔤 Guess the secret alphabet from A-Z

❤️ Attempts Left : {attempts}

GOOD LUCK 😎
"""

# Guess function
def guess_letter(guess):

    # If game over
    if game_state["game_over"]:

        return """
# 💀 GAME OVER

Please start a new game first.
"""

    # Validation
    guess = guess.upper()

    if len(guess) != 1 or not guess.isalpha():

        return """
# ⚠️ INVALID INPUT

Please enter ONE alphabet letter only!
"""

    secret = game_state["secret"]

    # Correct answer
    if guess == secret:

        game_state["game_over"] = True

        return f"""
# 🎉 YOU WIN!

✅ Correct Letter : {secret}

🏆 CONGRATULATIONS!
"""

    # Reduce attempt
    game_state["attempts"] -= 1

    # Hint
    if guess < secret:
        hint = "➡️ AFTER"

    else:
        hint = "⬅️ BEFORE"

    # Game over condition
    if game_state["attempts"] <= 0:

        game_state["game_over"] = True

        return f"""
# 💀 GAME OVER

❌ No attempts remaining!

🔐 The secret letter was :
# {secret}
"""

    # Continue game
    return f"""
# ❌ WRONG GUESS

💡 Hint : {hint}

❤️ Attempts Left :
{game_state["attempts"]}
"""

# Interface
with gr.Blocks() as demo:

    gr.Markdown("# 🔤 Alphabet Guess Lotto Game")

    level = gr.Radio(
        ["Easy", "Medium", "Hard"],
        label="🎚️ Choose Difficulty"
    )

    start_btn = gr.Button("🎮 Start Game")

    game_output = gr.Markdown()

    start_btn.click(
        start_game,
        inputs=level,
        outputs=game_output
    )

    guess_input = gr.Textbox(
        label="🔤 Enter Your Guess (A-Z)"
    )

    guess_btn = gr.Button("🎯 Submit Guess")

    guess_btn.click(
        guess_letter,
        inputs=guess_input,
        outputs=game_output
    )

# Launch app
demo.launch()