# -*- coding: utf-8 -*-
"""Lotto_Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZevYgFJP2Vk964dca-mdrvWOa6qzJfgU
"""

import random
import string

print("====================================")
print("🔤 WELCOME TO ALPHABET LOTTO GAME 🔤")
print("====================================")

# Player name
name = input("Enter your name: ")

# Choose difficulty
print("\nChoose Difficulty Level:")
print("1. Easy")
print("2. Medium")
print("3. Hard")

level = input("Select level (1/2/3): ")

# Difficulty setting
if level == "1":
    attempts = 10
    level_name = "Easy"

elif level == "2":
    attempts = 7
    level_name = "Medium"

else:
    attempts = 5
    level_name = "Hard"

# Generate secret letter
secret = random.choice(list(string.ascii_uppercase))

print(f"\n🎮 Game Started - {level_name} Mode")
print("Guess the secret alphabet from A-Z")
print(f"You have {attempts} chances.\n")

# Game loop
while attempts > 0:

    guess = input("Enter your guess: ").upper()

    # Validation
    if len(guess) != 1 or not guess.isalpha():

        print("⚠️ Please enter ONE alphabet letter only!\n")
        continue

    # Correct answer
    if guess == secret:

        print("\n🎉 CONGRATULATIONS!")
        print(f"✅ The secret letter was: {secret}")
        print("🏆 YOU WIN!")
        break

    # Reduce attempts
    attempts -= 1

    # Hint system
    if guess < secret:

        print("➡️ Hint: AFTER")

    else:

        print("⬅️ Hint: BEFORE")

    # Remaining attempts
    print(f"❤️ Remaining Chances: {attempts}\n")

# Game over
if attempts == 0:

    print("\n💀 GAME OVER")
    print(f"🔐 The secret letter was: {secret}")

print(f"\n🎉 Thanks for playing, {name}!")